name: PrefixSystem
author: Sr_Unknown
version: 1.2.4
main: unknown\prefix\Loader
api: 5.0.0
depend:
  - RankSystem
website: https://portafolio-pink-theta.vercel.app/

permissions:
  prefix.admin:
    default: op
    description: Allows the player to use the /prefix command
  prefix.user:
    default: true
    description: Allows the player to use the prefix